### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by guidorugo** [atareao/cpu-g#10]
Fresh install, xubuntu 19.04, installed thought apt repository. Running with sudo

```[Errno 2] No translation file found for domain: 'cpu-g'
Traceback (most recent call last):
  File "./cpu-g", line 42, in <module>
    cpug = CPUG()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 999, in __init__
    self.update_info()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1174, in update_info
    self.desktop_environment.set_text(inv.desktop_environment())
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/investigator.py", line 110, in desktop_environment
    elif self.is_running("xfce-mcs-manage"):
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/investigator.py", line 133, in is_running
    if re.search(process, x):
  File "/usr/lib/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by maty535** [comment]
Change the line of code:
from:
if re.search(process, x):

if re.search(process, x.decode('utf-8')):


fixed this problem, and I'm able to run cpu-g  also from terminal, or via remote x windows.

**Comment by atareao** [comment]
Fixed. Thanks for your report
