### ISSUE TITLE
Running without sudo returns TypeError

### ISSUE THREAD

**Issue by guidorugo** [atareao/cpu-g#11]
Fresh xubuntu 19.04. Installed thought apt repository.

```weed0@weed0:/opt/extras.ubuntu.com/cpu-g/bin$ ./cpu-g
[Errno 2] No translation file found for domain: 'cpu-g'
/opt/extras.ubuntu.com/cpu-g/share/cpu-g/distros/ubuntu.png
[Errno 2] No such file or directory: '/sys/class/power_supply/BAT0/charge_now'
[Errno 2] No such file or directory: '/sys/class/power_supply/BAT0/charge_now'
Traceback (most recent call last):
  File "./cpu-g", line 42, in <module>
    cpug = CPUG()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 999, in __init__
    self.update_info()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1318, in update_info
    self.start_battery_updater()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1346, in start_battery_updater
    self.get_battery_duration()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1079, in get_battery_duration
    inv.battery_info('charge-now')/1000000) + _(' Ah'))
TypeError: unsupported operand type(s) for /: 'str' and 'int'```

**Comment by Armag67** [comment]
Hello,

I had to slightly modify the two files:
1. /usr/share/cpu-g/src/cpug.py
2. /usr/share/cpu-g/src/investigator.py
to make this application work properly on my Manjaro 18.0.4, Xfce stable, kernel 4.19.66-1 box with french locale (with displaying Xorg version, good distro logo, battery charges: now, full, full design and power now).
Take a look at the two file in the attached tar.gz part and compare them with the original files with `Diffuse Merge Tool` for example.
[cpu-g-src.tar.gz](https://github.com/atareao/cpu-g/files/3567193/cpu-g-src.tar.gz)

**Comment by BriFuture** [comment]
Hi, I replaced the original `cpug.py` and `investigator.py` with your cede, it still crashed:

```
[Errno 2] No translation file found for domain: 'cpu-g'
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1180, in on_core_changed
    self.update_info_for_core(coren)
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1393, in update_info_for_core
    self.l1data.set_text(inv.sysdevcpu(i, 1, 'Data'))
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/investigator.py", line 287, in sysdevcpu
    (self.cpuinfo('coresnum'), coresinsysdev))
TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/cpu-g/bin/cpu-g", line 42, in <module>
    cpug = CPUG()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1003, in __init__
    self.update_info()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1191, in update_info
    self.update_info_for_core(0)
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1393, in update_info_for_core
    self.l1data.set_text(inv.sysdevcpu(i, 1, 'Data'))
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/investigator.py", line 287, in sysdevcpu
    (self.cpuinfo('coresnum'), coresinsysdev))
TypeError: not all arguments converted during string formatting
```

Environment Ubuntu 18.04 bonic

**Comment by Armag67** [comment]
There is a subtle bug in the sysdevcpu function in investigator.py. This bug only occur if /proc/cpuinfo and /sys/devices/system/cpu/ don't return the same number of cores. Then sysdevcpu function try to print:
`            print("Error: Cannot decide if the cores are %s or %s.\n" +`
`                  "Using the lowest value as the real cores number." %`
`                  (self.cpuinfo('coresnum'), coresinsysdev))`
which is buggy.
Try to replace these three lines by:
`            print("Error: Cannot decide if the cores are %s or %s.\n"`
`                  % (self.cpuinfo('coresnum'), coresinsysdev) +`
`                  "Using the lowest value as the real cores number.")`
But do not forget to respect the indentations, especially for the first line

**Comment by wyphan** [comment]
I was able to reproduce the error in @BriFuture's [comment](https://github.com/atareao/cpu-g/issues/11#issuecomment-552865213) on Ubuntu 18.04 by installing CPU-G from the PPA then running it in the terminal without `sudo`, even before applying @Armag67 's [first fix](https://github.com/atareao/cpu-g/issues/11#issuecomment-527254434).
```
[Errno 2] No translation file found for domain: 'cpu-g'
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1152, in on_core_changed
    self.update_info_for_core(coren)
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1366, in update_info_for_core
    self.l1data.set_text(inv.sysdevcpu(i, 1, 'Data'))
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/investigator.py", line 276, in sysdevcpu
    (self.cpuinfo('coresnum'), coresinsysdev))
TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/cpu-g/bin/cpu-g", line 42, in <module>
    cpug = CPUG()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 999, in __init__
    self.update_info()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1163, in update_info
    self.update_info_for_core(0)
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1366, in update_info_for_core
    self.l1data.set_text(inv.sysdevcpu(i, 1, 'Data'))
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/investigator.py", line 276, in sysdevcpu
    (self.cpuinfo('coresnum'), coresinsysdev))
TypeError: not all arguments converted during string formatting
```
Applying the first fix only shifts the line number for me.
```
[Errno 2] No translation file found for domain: 'cpu-g'
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1152, in on_core_changed
    self.update_info_for_core(coren)
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1366, in update_info_for_core
    self.l1data.set_text(inv.sysdevcpu(i, 1, 'Data'))
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/investigator.py", line 287, in sysdevcpu
    (self.cpuinfo('coresnum'), coresinsysdev))
TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/cpu-g/bin/cpu-g", line 42, in <module>
    cpug = CPUG()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 999, in __init__
    self.update_info()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1163, in update_info
    self.update_info_for_core(0)
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1366, in update_info_for_core
    self.l1data.set_text(inv.sysdevcpu(i, 1, 'Data'))
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/investigator.py", line 287, in sysdevcpu
    (self.cpuinfo('coresnum'), coresinsysdev))
TypeError: not all arguments converted during string formatting
```
Applying both the first fix and the [second fix](https://github.com/atareao/cpu-g/issues/11#issuecomment-568917018) finally solves the problem -- now it runs but gives an interesting terminal output, both without and with `sudo`.
```
[Errno 2] No translation file found for domain: 'cpu-g'
Error: Cannot decide if the cores are 12 or 10.
Using the lowest value as the real cores number.
Error: Cannot decide if the cores are 12 or 10.
Using the lowest value as the real cores number.
Error: Cannot decide if the cores are 12 or 10.
Using the lowest value as the real cores number.
Error: Cannot decide if the cores are 12 or 10.
Using the lowest value as the real cores number.
Error: Cannot decide if the cores are 12 or 10.
Using the lowest value as the real cores number.
Error: Cannot decide if the cores are 12 or 10.
Using the lowest value as the real cores number.
Error: Cannot decide if the cores are 12 or 10.
Using the lowest value as the real cores number.
Error: Cannot decide if the cores are 12 or 10.
Using the lowest value as the real cores number.
/opt/extras.ubuntu.com/cpu-g/share/cpu-g/distros/ubuntu.png
```
Here's an interesting bit: when I only applied the second fix (but not the first), I can run it without `sudo`, but running under `sudo` crashes with a different error message:
```
[Errno 2] No translation file found for domain: 'cpu-g'
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/cpu-g/bin/cpu-g", line 42, in <module>
    cpug = CPUG()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 999, in __init__
    self.update_info()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1174, in update_info
    self.desktop_environment.set_text(inv.desktop_environment())
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/investigator.py", line 110, in desktop_environment
    elif self.is_running("xfce-mcs-manage"):
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/investigator.py", line 133, in is_running
    if re.search(process, x):
  File "/usr/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```

Finally, to remove the interesting output, commit [073e93](https://github.com/atareao/cpu-g/commit/073e932ae7d96146363127056eff2f925873e6eb#diff-f6c9100dc3484366b5cb85ac2f4da9ad). For other PPA users out there: change line 269 in `/opt/extras.ubuntu.com/cpu-g/share/cpu-g/investigator.py` (line 280 after the first fix) from
```python
        coresinsysdev = str(
            len(re.findall("'cpu[0-9]'",
                           str(os.listdir("/sys/devices/system/cpu/")))))
```
to
```python
        coresinsysdev = str(
            len(re.findall("'cpu[0-9]+'",
                           str(os.listdir("/sys/devices/system/cpu/")))))
```

**Comment by HonoluluHenk** [comment]
still relevant
@atareao care to integrate this?
