### ISSUE TITLE
Unable to start cpu-g on lubuntu 18.04.04 LTS

### ISSUE THREAD

**Issue by asbachb** [atareao/cpu-g#17]
```
asbachb@ubuntu:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```

```
asbachb@ubuntu:~$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 13
model name	: Intel(R) Pentium(R) M processor 1.70GHz
stepping	: 8
microcode	: 0x20
cpu MHz		: 600.000
cache size	: 2048 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fdiv_bug	: no
f00f_bug	: no
coma_bug	: no
fpu		: yes
fpu_exception	: yes
cpuid level	: 2
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov clflush dts acpi mmx fxsr sse sse2 ss tm pbe nx bts cpuid est tm2 pti
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 1196.94
clflush size	: 64
cache_alignment	: 64
address sizes	: 32 bits physical, 32 bits virtual
power management:
```

```
asbachb@ubuntu:~$ sudo /opt/extras.ubuntu.com/cpu-g/bin/cpu-g 

(cpu-g:1461): dbind-WARNING **: 22:42:32.176: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
[Errno 2] No translation file found for domain: 'cpu-g'
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1152, in on_core_changed
    self.update_info_for_core(coren)
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1366, in update_info_for_core
    self.l1data.set_text(inv.sysdevcpu(i, 1, 'Data'))
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/investigator.py", line 279, in sysdevcpu
    re.findall("'index[0-9]*'", str(os.listdir(path))))
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/system/cpu/cpu0/cache/'
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/cpu-g/bin/cpu-g", line 42, in <module>
    cpug = CPUG()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 999, in __init__
    self.update_info()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1163, in update_info
    self.update_info_for_core(0)
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1366, in update_info_for_core
    self.l1data.set_text(inv.sysdevcpu(i, 1, 'Data'))
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/investigator.py", line 279, in sysdevcpu
    re.findall("'index[0-9]*'", str(os.listdir(path))))
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/system/cpu/cpu0/cache/'
```

**Comment by atareao** [comment]
Thanks for your report.

Fixed.
