### ISSUE TITLE
Does not launch in Pop OS 20.04

### ISSUE THREAD

**Issue by Electw** [atareao/cpu-g#21]
Installed it via PPA, application does not launch. It's likely due to Focal dropping Python 2, but is there a way to get the program running?

**Comment by atareao** [comment]
@Electw can you run from terminal????

`/opt/extras.ubuntu.com/cpu-g/bin/cpu-g`

Thanks

**Comment by Electw** [comment]
Nope. This is the output:
```
Gtk-Message: 23:28:35.494: Failed to load module "appmenu-gtk-module"
[Errno 2] No translation file found for domain: 'cpu-g'
[Errno 2] No such file or directory: '/sys/class/power_supply/BAT0/charge_now'
[Errno 2] No such file or directory: '/sys/class/power_supply/BAT0/charge_now'
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/cpu-g/bin/cpu-g", line 42, in <module>
    cpug = CPUG()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 999, in __init__
    self.update_info()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1318, in update_info
    self.start_battery_updater()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1346, in start_battery_updater
    self.get_battery_duration()
  File "/opt/extras.ubuntu.com/cpu-g/share/cpu-g/cpug.py", line 1079, in get_battery_duration
    inv.battery_info('charge-now')/1000000) + _(' Ah'))
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

**Comment by muhammadkholidb** [comment]
Got the same issue here, seems like no fix yet for this?

**Comment by mattkjames7** [comment]
I have the same issue with Linux Mint (Ubuntu 24.04)
