### ISSUE TITLE
Debian 10: missing dependencies and no translation file found

### ISSUE THREAD

**Issue by edbird** [atareao/cpu-g#22]
Missing dependencies: python3-matplotlib python3-psutil

Error

```
/cpu-g 
[Errno 2] No translation file found for domain: 'cpu-g'
Traceback (most recent call last):
  File "./cpu-g", line 42, in <module>
    cpug = CPUG()
  File "/home/ecb/cpu-g/src/cpug.py", line 999, in __init__
    self.update_info()
  File "/home/ecb/cpu-g/src/cpug.py", line 1177, in update_info
    self.distribution.set_text(inv.distro())
  File "/home/ecb/cpu-g/src/investigator.py", line 300, in distro
    return get_distro()
  File "/home/ecb/cpu-g/src/distro.py", line 39, in get_distro
    version_split = RELEASE_DATA["VERSION"].split(" ", maxsplit=1)
KeyError: 'VERSION'
```

**Comment by edbird** [comment]
I presume the ppa is for Ubuntu. I have no idea if it will break my system if I install it from this.

**Comment by stevexyz** [comment]
The best would be to make an official .deb packet  and put it into the release of github or the Debian distribution itself
