### ISSUE TITLE
Debian Stretch - Python3 KeyError

### ISSUE THREAD

**Issue by edbird** [atareao/cpu-g#23]
```
python3 cpu-g
[Errno 2] No translation file found for domain: 'cpu-g'
Traceback (most recent call last):
  File "cpu-g", line 42, in <module>
    cpug = CPUG()
  File "/home/ecb/cpu-g/src/cpug.py", line 999, in __init__
    self.update_info()
  File "/home/ecb/cpu-g/src/cpug.py", line 1177, in update_info
    self.distribution.set_text(inv.distro())
  File "/home/ecb/cpu-g/src/investigator.py", line 300, in distro
    return get_distro()
  File "/home/ecb/cpu-g/src/distro.py", line 39, in get_distro
    version_split = RELEASE_DATA["VERSION"].split(" ", maxsplit=1)
KeyError: 'VERSION'
```

**Comment by f-christo-a-ffer-t** [comment]
I guess you copied it directly from the prompt? "python3 'cpu-g'".
My guess is that it should have been "python3 'cpu -g'", so a space between cpu and -g.
I do this kind of errors all the time by myself, so that is why I am guessing that this is the problem.
I am downloading debian stretch to try, but slow internet connection :P

**Comment by f-christo-a-ffer-t** [comment]
The OS Debian stretch was realesed in 2017.
Last activity I can find on cpu-g is from around 2012.
So maybe your cpu-g version is to old to recognize debian 9?
