### ISSUE TITLE
Add support for arm64/aarch64

### ISSUE THREAD

**Issue by WMRamadan** [atareao/cpu-g#40]
Problem:
The application currently crashes when trying to run on arm64 cpu on Debian with the following crash dump:
```
[Errno 2] No translation file found for domain: 'cpu-g'
/home/<user>/cpu-g/src/cpug.py:72: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "n_rows, n_columns, homogeneous" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  table11 = Gtk.Table(3, 3, False)
/home/<user>/cpu-g/src/cpug.py:74: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Vendor'))
/home/<user>/cpu-g/src/cpug.py:75: DeprecationWarning: Gtk.Misc.set_alignment is deprecated
  label.set_alignment(0, 0.5)
/home/<user>/cpu-g/src/cpug.py:85: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Model'))
/home/<user>/cpu-g/src/cpug.py:96: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Core Speed'))
/home/<user>/cpu-g/src/cpug.py:114: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "n_rows, n_columns, homogeneous" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  table12 = Gtk.Table(3, 6, False)
/home/<user>/cpu-g/src/cpug.py:116: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Family'))
/home/<user>/cpu-g/src/cpug.py:128: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Model'))
/home/<user>/cpu-g/src/cpug.py:140: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Stepping'))
/home/<user>/cpu-g/src/cpug.py:152: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Flags'))
/home/<user>/cpu-g/src/cpug.py:163: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Bogomips'))
/home/<user>/cpu-g/src/cpug.py:174: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Width'))
/home/<user>/cpu-g/src/cpug.py:189: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "n_rows, n_columns, homogeneous" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  table13 = Gtk.Table(4, 2, False)
/home/<user>/cpu-g/src/cpug.py:191: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('L1 Data'))
/home/<user>/cpu-g/src/cpug.py:202: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('L1 Instruction'))
/home/<user>/cpu-g/src/cpug.py:213: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Level 2'))
/home/<user>/cpu-g/src/cpug.py:224: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Level 3'))
/home/<user>/cpu-g/src/cpug.py:238: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "n_rows, n_columns, homogeneous" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  table14 = Gtk.Table(1, 3, False)
/home/<user>/cpu-g/src/cpug.py:240: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Number of cores'))
/home/<user>/cpu-g/src/cpug.py:266: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "n_rows, n_columns, homogeneous" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  table21 = Gtk.Table(2, 2, False)
/home/<user>/cpu-g/src/cpug.py:268: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Vendor'))
/home/<user>/cpu-g/src/cpug.py:279: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Model'))
/home/<user>/cpu-g/src/cpug.py:292: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "n_rows, n_columns, homogeneous" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  table22 = Gtk.Table(3, 2, False)
/home/<user>/cpu-g/src/cpug.py:294: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Vendor'))
/home/<user>/cpu-g/src/cpug.py:305: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Version'))
/home/<user>/cpu-g/src/cpug.py:316: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Date'))
/home/<user>/cpu-g/src/cpug.py:332: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "n_rows, n_columns, homogeneous" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  table31 = Gtk.Table(8, 2, False)
/home/<user>/cpu-g/src/cpug.py:334: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Total'))
/home/<user>/cpu-g/src/cpug.py:346: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Available'))
/home/<user>/cpu-g/src/cpug.py:368: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Used'))
/home/<user>/cpu-g/src/cpug.py:389: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Free'))
/home/<user>/cpu-g/src/cpug.py:410: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Active'))
/home/<user>/cpu-g/src/cpug.py:423: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Inactive'))
/home/<user>/cpu-g/src/cpug.py:436: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Buffers'))
/home/<user>/cpu-g/src/cpug.py:449: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Cached'))
/home/<user>/cpu-g/src/cpug.py:463: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "n_rows, n_columns, homogeneous" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  table32 = Gtk.Table(8, 2, False)
/home/<user>/cpu-g/src/cpug.py:465: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Total'))
/home/<user>/cpu-g/src/cpug.py:478: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Used'))
/home/<user>/cpu-g/src/cpug.py:498: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Free'))
/home/<user>/cpu-g/src/cpug.py:518: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Sin'))
/home/<user>/cpu-g/src/cpug.py:531: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Sout'))
/home/<user>/cpu-g/src/cpug.py:550: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "n_rows, n_columns, homogeneous" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  table41 = Gtk.Table(7, 3, False)
/home/<user>/cpu-g/src/cpug.py:552: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Hostname'))
/home/<user>/cpu-g/src/cpug.py:563: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Architecture'))
/home/<user>/cpu-g/src/cpug.py:574: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Kernel'))
/home/<user>/cpu-g/src/cpug.py:585: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('GCC Version'))
/home/<user>/cpu-g/src/cpug.py:596: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Uptime'))
/home/<user>/cpu-g/src/cpug.py:607: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Xorg Server version'))
/home/<user>/cpu-g/src/cpug.py:618: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Resolution'))
/home/<user>/cpu-g/src/cpug.py:630: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Distribution'))
/home/<user>/cpu-g/src/cpug.py:641: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Desktop environment'))
/home/<user>/cpu-g/src/cpug.py:653: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Window manager'))
/home/<user>/cpu-g/src/cpug.py:676: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "n_rows, n_columns, homogeneous" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  table51 = Gtk.Table(4, 2, False)
/home/<user>/cpu-g/src/cpug.py:678: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Graphic Controller'))
/home/<user>/cpu-g/src/cpug.py:689: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('OpenGL Vendor'))
/home/<user>/cpu-g/src/cpug.py:700: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('OpenGL renderer'))
/home/<user>/cpu-g/src/cpug.py:711: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('OpenGL version'))
/home/<user>/cpu-g/src/cpug.py:735: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "n_rows, n_columns, homogeneous" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  table611 = Gtk.Table(8, 4, False)
/home/<user>/cpu-g/src/cpug.py:737: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Manufacturer'))
/home/<user>/cpu-g/src/cpug.py:749: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Model name'))
/home/<user>/cpu-g/src/cpug.py:761: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Serial number'))
/home/<user>/cpu-g/src/cpug.py:773: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Technology'))
/home/<user>/cpu-g/src/cpug.py:785: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Estimated time remaining'))
/home/<user>/cpu-g/src/cpug.py:797: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Estimated battery discharge time'))
/home/<user>/cpu-g/src/cpug.py:809: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Battery level'))
/home/<user>/cpu-g/src/cpug.py:829: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Capacity level'))
/home/<user>/cpu-g/src/cpug.py:841: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Voltage now'))
/home/<user>/cpu-g/src/cpug.py:853: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Minimum voltage design'))
/home/<user>/cpu-g/src/cpug.py:865: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Charge now'))
/home/<user>/cpu-g/src/cpug.py:877: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Charge full'))
/home/<user>/cpu-g/src/cpug.py:889: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Charge full design'))
/home/<user>/cpu-g/src/cpug.py:901: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(_('Current now'))
/home/<user>/cpu-g/src/cpug.py:923: DeprecationWarning: Gtk.ScrolledWindow.add_with_viewport is deprecated
  self.srolled_windows_for_plot.add_with_viewport(canvas)
/home/<user>/cpu-g/src/cpug.py:941: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "n_rows, n_columns, homogeneous" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  table991 = Gtk.Table(9, 1, False)
Traceback (most recent call last):
  File "/home/<user>/cpu-g/src/cpug.py", line 1152, in on_core_changed
    self.update_info_for_core(coren)
  File "/home/<user>/cpu-g/src/cpug.py", line 1357, in update_info_for_core
    self.vendor.set_text(inv.cpuinfo('vendor', i))
  File "/home/<user>/cpu-g/src/investigator.py", line 248, in cpuinfo
    if vendor[core] == 'AuthenticAMD':
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/<user>/cpu-g/src/cpug.py", line 1393, in <module>
    cpug = CPUG()
  File "/home/<user>/cpu-g/src/cpug.py", line 999, in __init__
    self.update_info()
  File "/home/<user>/cpu-g/src/cpug.py", line 1163, in update_info
    self.update_info_for_core(0)
  File "/home/<user>/cpu-g/src/cpug.py", line 1357, in update_info_for_core
    self.vendor.set_text(inv.cpuinfo('vendor', i))
  File "/home/<user>/cpu-g/src/investigator.py", line 248, in cpuinfo
    if vendor[core] == 'AuthenticAMD':
IndexError: list index out of range
```

Specs:
- CPU = Apple M1
- Hypervisor = UTM/QEMU
- OS/Distro = Debian 11 aarch64
- Kernel = 5.10.0-21-arm64
- Python = 3.9.2

**Comment by atareao** [comment]
not pllaned
